---
- debug:
    msg:
    - "ansible_os_family:                     {{ ansible_os_family }}"
    - "ansible_distribution:                  {{ ansible_distribution }}"
    - "ansible_distribution_major_version:    {{ ansible_distribution_major_version }}"

# @todo : Centos-8 has issues installing vnstat
#- name: Include distribution-specific tasks (if they exist)
#  include_tasks: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
#  when: ansible_distribution == 'CentOS'
#    and ansible_distribution_major_version == '8'
#
#- name: Include OS-family-specific variables
#  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
#  when: ansible_distribution == 'CentOS'
#    and ansible_distribution_major_version == '8'

- name: Download vnstat
  get_url:
   # These come from vars/{ansible_distribution}-{ansible_distribution_major_version}.yml
    url: "{{ package_source }}"
    dest: "{{ download_dest }}"
  when: ansible_distribution == 'CentOS'
    and ansible_distribution_major_version == '8'

- name: Install vnstat to collect stats on system bandwidth
  package:
    name: vnstat
    state: present
    update_cache: true

- name: Create the initial database for vnstat
  shell: >
    /usr/bin/vnstat -u -i {{ ansible_default_ipv4.interface }}
  args:
    creates: /var/lib/vnstat/{{ ansible_default_ipv4.interface }}
  when: ansible_os_family == 'RedHat'

- name: Start and enable the vnstat service at boot
  service:
    name: vnstat
    state: started
    enabled: true
